call Pl#Match#Add('command_t'      , 'bufname("%")', 'GoToFile')
call Pl#Match#Add('ft_help'        , '&ft'         , 'help')
call Pl#Match#Add('ft_man'         , '&ft'         , 'man')
call Pl#Match#Add('ft_qf'          , '&ft'         , 'qf')
call Pl#Match#Add('gundo_preview'  , 'bufname("%")', '__Gundo_Preview__')
call Pl#Match#Add('gundo_tree'     , 'bufname("%")', '__Gundo__')
call Pl#Match#Add('lustyexplorer'  , 'bufname("%")', '\[LustyExplorer-Buffers\]')
call Pl#Match#Add('minibufexplorer', 'bufname("%")', '\-MiniBufExplorer\-')
call Pl#Match#Add('tagbar'         , 'bufname("%")', '__Tagbar__')
